특징 교차(feature cross) - 2개 이상의 개별 feature를 곱하거나 결합하여 새로운 합성 feature를 만드는 것
* x3 = x1 * x2
* goal = 데이터 간의 interaction을 모델에 직접 알려주기 위함

In [1]:
%pip install google-cloud-bigquery pyarrow pandas db-dtypes

Requirement already satisfied: google-cloud-bigquery in /opt/homebrew/lib/python3.12/site-packages (3.40.1)
Requirement already satisfied: pyarrow in /opt/homebrew/lib/python3.12/site-packages (23.0.0)
Requirement already satisfied: pandas in /opt/homebrew/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: db-dtypes in /opt/homebrew/lib/python3.12/site-packages (1.5.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (2.29.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /opt/homebrew/lib/python3.12/site-packages (from google-cloud-bigquery) (2.48.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/homebrew/lib/python3.12/site-packages (from google-cloud-bigquery) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/homebrew/lib/python3.12/site-packages (from google-cloud-bigquery) (2.8.0)
Requirement already satisfied: packaging>=24.2.0 in /opt/homebrew/lib/python3.12/site-packages (from google-cloud-bigquery) (24.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /Users/hobongs/Library/Python/3.12/lib/python/site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /opt/homebrew/lib/python3.12/site-packages (from google-cloud-bigquery) (2.32.5)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.72.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.27.1)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.78.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.78.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/homebrew/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/homebrew/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (46.0.5)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/homebrew/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (4.9.1)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /opt/homebrew/lib/python3.12/site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: typing-extensions~=4.12 in /opt/homebrew/lib/python3.12/site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: six>=1.5 in /Users/hobongs/Library/Python/3.12/lib/python/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/homebrew/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2025.4.26)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/homebrew/lib/python3.12/site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/lib/python3.12/site-packages (from pandas) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/lib/python3.12/site-packages (from pandas) (2025.3)
Requirement already satisfied: cffi>=2.0.0 in /opt/homebrew/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (2.0.0)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (3.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install google-cloud-bigquery-storage

Requirement already satisfied: google-cloud-bigquery-storage in /opt/homebrew/lib/python3.12/site-packages (2.36.1)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-bigquery-storage) (2.29.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1 in /opt/homebrew/lib/python3.12/site-packages (from google-cloud-bigquery-storage) (2.48.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /opt/homebrew/lib/python3.12/site-packages (from google-cloud-bigquery-storage) (1.78.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/homebrew/lib/python3.12/site-packages (from google-cloud-bigquery-storage) (1.27.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /opt/homebrew/lib/python3.12/site-packages (from google-cloud-bigquery-storage) (6.33.5)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-bigquery-storage) (1.72.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-bigquery-storage) (2.32.5)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /opt/homebrew/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-bigquery-storage) (1.78.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/homebrew/lib/python3.12/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/homebrew/lib/python3.12/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (46.0.5)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/homebrew/lib/python3.12/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (4.9.1)
Requirement already satisfied: typing-extensions~=4.12 in /opt/homebrew/lib/python3.12/site-packages (from grpcio<2.0.0,>=1.33.2->google-cloud-bigquery-storage) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/homebrew/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-bigquery-storage) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-bigquery-storage) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-bigquery-storage) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-bigquery-storage) (2025.4.26)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/homebrew/lib/python3.12/site-packages (from rsa<5,>=3.1.4->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (0.6.2)
Requirement already satisfied: cffi>=2.0.0 in /opt/homebrew/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (2.0.0)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (3.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os
from dotenv import load_dotenv


load_dotenv()

# 시스템 환경 변수에 구글 인증 키 경로 직접 등록
# 매직 명령어는 이 'GOOGLE_APPLICATION_CREDENTIALS'라는 이름을 찾아 인증합니다.
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = os.getenv('BIG_QUERY_KEY_PATH')

In [5]:
from google.cloud import bigquery

In [6]:
bq = bigquery.Client()
dataset = bigquery.Dataset(bq.dataset("babyweight"))

try:
  bq.create_dataset(dataset)
  print("Dataset created.")
except:
  print("Dataset already exists.")

Dataset already exists.

In [10]:
%load_ext google.cloud.bigquery

project_id = os.getenv('BIG_QUERY_PROJECT_ID')

The google.cloud.bigquery extension is already loaded. To reload it, use:
  %reload_ext google.cloud.bigquery

In [11]:
%%bigquery --project $project_id

SELECT schema_name 
FROM `region-us`.INFORMATION_SCHEMA.SCHEMATA;

/opt/homebrew/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
/opt/homebrew/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2714: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

  schema_name
0  babyweight
1        temp

In [12]:
%%bigquery --project $project_id
CREATE SCHEMA IF NOT EXISTS babyweight
OPTIONS(location="US");

/opt/homebrew/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)

Empty DataFrame
Columns: []
Index: []

In [13]:
%%bigquery --project $project_id
CREATE OR REPLACE TABLE
  babyweight.babyweight_data AS
SELECT
  weight_pounds,
  CAST(is_male AS STRING) AS is_male,
  mother_age,
  CASE
    WHEN plurality = 1 THEN "Single(1)"
    WHEN plurality = 2 THEN "Twins(2)"
    WHEN plurality = 3 THEN "Triplets(3)"
    WHEN plurality = 4 THEN "Quadruplets(4)"
    WHEN plurality = 5 THEN "Quintuplets(5)"
  END AS plurality,
  gestation_weeks,
  CAST(mother_race AS STRING) AS mother_race,
  FARM_FINGERPRINT(
    CONCAT(
      CAST(year AS STRING),
      CAST(month AS STRING)
    )
  ) AS hashmonth
FROM
  `bigquery-public-data.samples.natality`
WHERE
  year > 2000
  AND weight_pounds > 0
  AND mother_age > 0
  AND plurality > 0
  AND gestation_weeks > 0

/opt/homebrew/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)

Empty DataFrame
Columns: []
Index: []

In [14]:
%%bigquery --project $project_id
CREATE OR REPLACE TABLE
  babyweight.babyweight_data_train AS
SELECT
  weight_pounds,
  is_male,
  mother_age,
  plurality,
  gestation_weeks,
  mother_race
FROM
  babyweight.babyweight_data
WHERE
  ABS(MOD(hashmonth, 4)) < 3

/opt/homebrew/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)

Empty DataFrame
Columns: []
Index: []

In [15]:
%%bigquery --project $project_id
CREATE OR REPLACE TABLE
  babyweight.babyweight_data_eval AS
SELECT
  weight_pounds,
  is_male,
  mother_age,
  plurality,
  gestation_weeks,
  mother_race
FROM
  babyweight.babyweight_data
WHERE
  ABS(MOD(hashmonth, 4)) = 3

/opt/homebrew/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%bigquery --project $project_id
DROP MODEL IF EXISTS `babyweight.natality_model`;

In [18]:
%%bigquery --project $project_id
DROP MODEL IF EXISTS `babyweight.natality_model`;

/opt/homebrew/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py:2170: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  query_result = wait_for_query(self, progress_bar_type, max_results=max_results)

Empty DataFrame
Columns: []
Index: []

In [19]:
%%bigquery --project $project_id

CREATE OR REPLACE MODEL `babyweight.natality_model`
OPTIONS
  (MODEL_TYPE="DNN_REGRESSOR",
    HIDDEN_UNITS=[64, 32],
    INPUT_LABEL_COLS=["weight_pounds"],
    BATCH_SIZE=32,
    DATA_SPLIT_METHOD="NO_SPLIT") AS
SELECT
  weight_pounds,
  is_male,
  plurality,
  gestation_weeks,
  mother_age,
  CAST(mother_race AS string) AS mother_race
FROM
  babyweight.babyweight_data_train

Executing query with job ID: 0f15c89a-5303-43d1-ab07-30643bb08e8f
Query executing: 1.28s

ERROR:
 400 Concurrent model update with retrain is not supported.; reason: invalidQuery, location: query, message: Concurrent model update with retrain is not supported.

Location: US
Job ID: 0f15c89a-5303-43d1-ab07-30643bb08e8f

In [21]:
%%bigquery --project $project_id
SELECT * FROM `babyweight.INFORMATION_SCHEMA.MODELS`
WHERE model_name = 'natality_model';

Executing query with job ID: 5750cae8-6a3b-4225-9224-28e7ed0f5b9d
Query executing: 1.41s

ERROR:
 403 Access Denied: Table babyweight:INFORMATION_SCHEMA.MODELS: User does not have permission to query table babyweight:INFORMATION_SCHEMA.MODELS, or perhaps it does not exist.; reason: accessDenied, message: Access Denied: Table babyweight:INFORMATION_SCHEMA.MODELS: User does not have permission to query table babyweight:INFORMATION_SCHEMA.MODELS, or perhaps it does not exist.

Location: US
Job ID: 5750cae8-6a3b-4225-9224-28e7ed0f5b9d

In [22]:
query = """
SELECT
  *, SQRT(mean_squared_error) AS rmse
FROM
  ML.EVALUATE(MODEL `babyweight.natality_model`,
    (
    SELECT
      weight_pounds,
      is_male,
      plurality,
      gestation_weeks,
      mother_age,
      CAST(mother_race AS STRING) AS mother_race
    FROM
      babyweight.babyweight_data_eval ))
"""

In [23]:
df = bq.query(query).to_dataframe()
df.head()

,mean_absolute_error,mean_squared_error,mean_squared_log_error,median_absolute_error,r2_score,explained_variance,rmse
0,0.792551,1.03993,0.017722,0.648038,0.402351,0.403979,1.01977

빅쿼리에서 feature cross 사용해보기